### ISSUE TITLE
Site is harder to navigate now that all pages have the title "GraalVM"

### ISSUE THREAD

**Issue by jryans** [graalvm/graalvm-website#10]
A while ago (earlier in 2021), every documentation page included the individual page title in the `<title>` tag, making it easy to distinguish different pages when opened in several tabs. However, this appears to have regressed at some point (perhaps in https://github.com/graalvm/graalvm-website/commit/5cf1ce102a2a9dd42511f7cb543b7409399542f8), and now every page simply uses "GraalVM" in title.

Please restore the individual page title to the title tag for easier navigation. For example, https://www.graalvm.org/tools/ could use  the link title "Debugging and Monitoring Tools" or perhaps include a suffix to denote the site, such as "Debugging and Monitoring Tools | GraalVM".

**Comment by olyagpl** [comment]
Hello Ryan,
That was an intentional change. I'll see what we can do here.

**Comment by jryans** [comment]
Aha, I see. 😓 Please do consider restoring the individual page title in the title tag. If you look around at nearly any developer documentation site, I think you will find that they all include the page’s title in the title tag.

**Comment by nirvdrum** [comment]
This also messes up the browser history. If I try to select a previous page to visit, all the options just say "GraalVM", making navigation unduly difficult.

**Comment by olyagpl** [comment]
We will address the problem right after the release on Jan 18! Thanks for sharing your experience.

**Comment by olyagpl** [comment]
@jryans, the individual page titles are restored now. The `title` value is added in the YAML header automatically. 
Thanks for the request.

**Comment by jryans** [comment]
Looks great, thanks so much for working on this! 😄
