### ISSUE TITLE
Where is the jshell-espresso demo?

### ISSUE THREAD

**Issue by joinr** [graalvm/graalvm-website#4]
Under the "Demo Applications/Mixing AOT for JIT and Java":

>1. Clone the project with the demo applications and navigate to the following directory: espresso/jshell

This project reference doesn't appear to exist anywhere in the document or on the web/github.  The rest of the section discusses it.  Is there a repository somewhere?

**Comment by ezzarghili** [comment]
Demos are under the `graalvm-demos` repo https://github.com/graalvm/graalvm-demos/tree/master/espresso-jshell
