### ISSUE TITLE
Link https://github.com/graalvm/graalvm-ce-builds/releases/latest now leads to a old release

### ISSUE THREAD

**Issue by denis-komarov** [graalvm/graalvm-website#7]
Link [https://github.com/graalvm/graalvm-ce-builds/releases/latest](https://github.com/graalvm/graalvm-ce-builds/releases/latest) now leads to a release 21.0.0.2 but the last release is now 21.2.0

**Comment by olyagpl** [comment]
Thanks for heads up!
