### ISSUE TITLE
test examples of classes link is broken

### ISSUE THREAD

**Issue by sudoHackIn** [graalvm/graalvm-website#9]
Hi, while reading GraalVM documentation(https://www.graalvm.org/reference-manual/native-image/ClassInitialization/#automatic-initialization-of-safe-classes) found, that the link to 

> A test that shows examples of classes that are proven safe can be found here.

is broken
https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.test/src/com/oracle/svm/test/TestClassInitializationMustBeSafe.java

**Comment by olyagpl** [comment]
@sudoHackIn, a good catch. I'll correct!

**Comment by olyagpl** [comment]
@sudoHackIn, the link has been fixed https://www.graalvm.org/dev/reference-manual/native-image/ClassInitialization/. Thank you!
